### ISSUE TITLE
App crashes when attempting to click on an issue

### ISSUE THREAD

**Issue by RandomlyKnighted** [michelsalib/Gi7#56]
When I click on an issue in the app in order to read the full description I get the following error message:

![error_when_clicking_on_an_issue](https://cloud.githubusercontent.com/assets/2483249/5706982/ab3c4a58-9a4a-11e4-9efd-b6cf0e99ac52.jpg)

**Comment by NPadrutt** [comment]
Just submitted a fix for this.
