### ISSUE TITLE
Add busy indicator to login view

### ISSUE THREAD

**Issue by NPadrutt** [michelsalib/Gi7#60]
If you click on login nothing indicates that the app is doing something. An indicator in the system tray would help here.

**Comment by RandomlyKnighted** [comment]
When I log in there is a very quick "loading..." that appears at the very top of the screen then disappears.

**Comment by NPadrutt** [comment]
it doens't always appear here. Sometimes I get a "wrong credentials" message. After another click I can log in (without changing the credentials). Then there is no indicator.

**Comment by RandomlyKnighted** [comment]
Sounds like it's an issue with detecting when to display that message. Do you want to look into this?

**Comment by NPadrutt** [comment]
The whole login process seems sometimes a bit instable. I'll see if I can find something.

**Comment by NPadrutt** [comment]
I subimitted a change who should fix this.
