### ISSUE TITLE
Crash if click on issue

### ISSUE THREAD

**Issue by NPadrutt** [michelsalib/Gi7#61]
In the message dialog it states args EventArgsObject reference is not set to an instance of an object.

**Comment by RandomlyKnighted** [comment]
There is already an issue opened for this. #56

**Comment by NPadrutt** [comment]
uh, sorry

**Comment by RandomlyKnighted** [comment]
No worries, I've added some new issues and updated several others. Feel free to look over my fork to see what additional I've found since I started working on the project.
