### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by NPadrutt** [michelsalib/Gi7#66]
There are some updates for the used libraries e.g. MVVM Light. This inclues a bump from 4.x to 5.x for MVVM Light. I think we should update that.

**Comment by RandomlyKnighted** [comment]
Good idea, I didn't notice that until I synced with the last merge and started getting errors about things being out of date.

**Comment by RandomlyKnighted** [comment]
@NPadrutt When you update your dependencies, please make sure that you update nuget. When I resynced my fork with the main repo I ended up with whatever version of nuget you had. I had to update nuget in order to start getting clean builds again.

**Comment by NPadrutt** [comment]
What do you mean exactly with update nuget? I know nuget the way that I just change the version in the nuget config and you can download the respective version via nuget. Enable restore on build can help here. Or do you mean something different?

**Comment by RandomlyKnighted** [comment]
I just navigated to the project's .nuget folder via the command prompt and ran the following command

```
nuget.exe update -self
```

This updated nuget from version 1.7 to 2.8.3. This was the only way I was able to fix the problem. Your way might work too, it's worth a shot. I just wanted to make sure that we all have the same version in order to prevent this from happening if anyone else were to come on to the project.

**Comment by NPadrutt** [comment]
Ah I guess that's the version of nuget itself. Wasn't aware that I didn't something there. Sorry for the hassle.

**Comment by RandomlyKnighted** [comment]
It's fine. I wasn't aware of it either until I synced everything.

**Comment by NPadrutt** [comment]
I did the update. But now I have a problem with the login view. The command doesn't get executed. But the binding here is done via the command attribute of the button o.O anyone an idea?

<pre><code> <Button Content="Login" Command="{Binding LoginCommand}" /> </code></pre>

**Comment by RandomlyKnighted** [comment]
Did you figure out what he issue was with the command attribute?

**Comment by NPadrutt** [comment]
yes and no. There was a problem in calling the delegate when it was written inline. As soon as I made a method and called it everything went well. you can see it in the LoginPanelViewModel.
