### ISSUE TITLE
BindableApplicationBar Watch/Unwatch does not accurately reflect GitHub website

### ISSUE THREAD

**Issue by RandomlyKnighted** [michelsalib/Gi7#73]
For example, because I have contributed to the Gi7 project GitHub has me down as "watching" the repo. In the app, however, it's apparently is not checking to see if I'm already watching the repo because when I go to the Gi7 project the "watch" button is enabled and the "unwatch" button is disabled. 

FYI:
The Android GitHub app does not have this feature so it is up to the team as to whether or not we keep this and fix it or if we remove it altogether. Personally, I'm more inclined to remove it and just keep it simple with a share and possibly adding the ability to start the repository later on. This would keep the application simple and also help keep us on track with the GitHub applications that are on other platforms.

**Comment by NPadrutt** [comment]
ah, good you wrote this down. I saw it yesterday but forgot to create an issue.

Since it doesn't work at the moment I tend to remove it and create a issue for a proper implementation.

**Comment by RandomlyKnighted** [comment]
Ok is this a feature that you would want in the app?

Generally I just let the GitHub website take care of all the watching and unwatching for me so I'm fine with removing it and implementing it later or just removing it altogether.

@michelsalib, @AlbertoMonteiro  what about you two?

**Comment by NPadrutt** [comment]
mh, never felt like I want to use it. But maybe there are people who do so. My intention with the "make an issue" was more about create the opportunity to talk again about. but maybe we should just remove it =)

**Comment by michelsalib** [comment]
I would definitely understand removing it for now, reaching for a more stable app before reintegrating secondary features.

**Comment by AlbertoMonteiro** [comment]
The best code that you write, is the code that you remove :P
Remove it!!!!
:+1:
