### ISSUE TITLE
Add Issue broken

### ISSUE THREAD

**Issue by NPadrutt** [michelsalib/Gi7#77]
The app reacts like everything went well but the issue isn't created.

**Comment by RandomlyKnighted** [comment]
Since this feature is broken it would be a good one to refactor using Octokit. That way we only have to fix it one time.

**Comment by NPadrutt** [comment]
yeah, I had the same thought.

**Comment by NPadrutt** [comment]
unfortunately there is currently no support for the issue api. so i will try to fix the error in the current implementation. maybe it's a consideration to commit that code to the octokit code.

**Comment by NPadrutt** [comment]
Nevermind, found it =)

**Comment by NPadrutt** [comment]
this should be fixed.
